#ifndef PIN_MAP_H
#define PIN_MAP_H

#define PIN_T inline constexpr uint8_t
namespace pins {
    PIN_T I2S_DATA = GPIO_NUM_26;
    PIN_T I2S_BCK = GPIO_NUM_25;
    PIN_T I2S_LRC = GPIO_NUM_4;
    PIN_T DISPLAY_DC = GPIO_NUM_7;
    PIN_T DISPLAY_CS = GPIO_NUM_8;
    PIN_T LIGHTS = GPIO_NUM_13;
    PIN_T DISPLAY_RST = GPIO_NUM_12;
    PIN_T MATRIX_CS = GPIO_NUM_27;
    PIN_T LEFT_BUTTON = GPIO_NUM_34;
    PIN_T MIDDLE_BUTTON = GPIO_NUM_39;
    PIN_T RIGHT_BUTTON = GPIO_NUM_36;
}

#endif //PIN_MAP_H
